baseURL = 'https://vankod.dev/'
languageCode = 'en-us'
title = 'vankod'

[Params]
  favicon = "img/favicon.ico"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = 'monokai'
    tabWidth = 2
